---
# tasks file for ssh-configuration
- name: create the ssh conf dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, ssh_config_dir) | path_join }}"
    state: directory
    mode: '0700'

- name: copy the ssh files
  copy:
    src: "{{ item }}"
    dest: "{{ (ansible_user_dir, ssh_config_dir, item ) | path_join }}"
    mode: u=r,g=,o=
  with_items:
    - "config"
    - "config_mathphys"
    - "config_mathphys_teleport_proxy"

- name: copy all the scripts into the script_dir
  copy:
    # the trailing slash ensures that all the folder content
    # and not the folder itself is copied!
    src: ssh-keys/
    dest: "{{ (ansible_user_dir, ssh_config_dir) | path_join }}"
    mode: u=rw,g=,o=
