---

- hosts: 127.0.0.1
  connection: local
  tags:
    - always
  tasks:
    - name: include the host-specific vars
      include_vars: "{{ ('vars', item) | path_join }}"
      with_first_found:
        - files:
            # allows for specific configs per host
            - "{{ ansible_hostname }}.yml"

    - name: include the default vars
      include_vars: "defaults.yml"

- name: "Step 1: Provision the essentials"
  hosts: 127.0.0.1
  connection: local
  tags:
    - bootstrap
  roles:
    - git-configuration
    - ssh-configuration
    - shell-configuration
    - custom-scripts

- name: "Step 2: Configure the rest"
  hosts: 127.0.0.1
  connection: local
  roles:
    - nvim-configuration
    - polybar-configuration
    - gopass-configuration
    - i3-configuration
    - fonts-configuration
    - irc-configuration
