---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - include_vars: "{{ ('vars', item) | path_join }}"
      with_first_found:
        - files:
            # allows for specific configs per host
            - "{{ ansible_hostname }}.yml"
    - include_vars: "defaults.yml"

- name: Include the "01_bootstrap.yml" Playbook
  ansible.builtin.import_playbook: 01_bootstrap.yml


- name: "Step 2: Configure the rest"
  hosts: 127.0.0.1
  connection: local
  roles:
    - nvim-configuration
    - polybar-configuration
    - gopass-configuration
    - i3-configuration
