---

- hosts: 127.0.0.1
  connection: local
  tasks:
  - include_vars: "{{ ('vars', item) | path_join }}"
    with_first_found:
      - files:
          # allows for specific configs per host
          - "{{ ansible_hostname }}.yml"

- name: "Step 2: Configure the rest"
  hosts: 127.0.0.1
  connection: local
  roles:
    # from bootstrap
    - git-configuration
    - ssh-configuration
    - shell-configuration
    - custom-scripts
    # other
    - nvim-configuration
    - polybar-configuration
    - gopass-configuration
    - i3-configuration
