---
# vars file for i3-install

greeter_unit_name: gdm.service

base_packages:
  - ansible
  - ansible-lint
  - bat
  - bpython
  - cgdb
  - cmake
  - cups
  - cups-pdf
  - curl
  - docker
  - docker-compose
  - exfatprogs
  - file
  - findutils
  - fwupd
  - gcc
  - gdb
  - git
  - golang
  - grep
  - gzip
  - htop
  - hugo
  - iotop
  - libmtp-common
  - libmtp-dev
  - libnfs-utils
  - linux-headers-amd64
  - linux-image-amd64
  - lxappearance
  - man-db
  - mlocate
  - moreutils
  - nano
  - ncdu
  - neofetch
  - neovim
  - netcat-traditional
  - nmap
  - ntfs-3g
  - openssh-client
  - openssh-server
  - pandoc
  - pdftk
  - python3
  - python3-dbus
  - python3-matplotlib
  - python3-neovim
  - python3-pip
  - qemu
  - qrencode
  - ranger
  - r-base
  - ripgrep
  - ripgrep
  - rkhunter
  - rsync
  - sed
  - sl
  - speedtest-cli
  - subversion
  - sudo
  - tmux
  - tree
  - unp
  - unrar
  - wget
  - wget
  - whois
  - yamllint
  - yapf3
  - youtube-dl
  - zbar-tools
  - zsh
  - zsh-syntax-highlighting

desktop_packages:
  - audacity
  - evince
  - file-roller
  - firefox-esr
  - gimp
  - gopass
  - gparted
  - kde-spectacle
  - kdenlive
  - libreoffice
  - mpv
  - obs-studio
  - pdfpc
  - qutebrowser
  - screenfetch
  - sxiv
  - telegram-desktop
  - terminator
  - thunderbird
  - virt-manager
  - vlc
  - weechat
  - x11-xserver-utils
  - xbacklight
  - xclip
  - xdotool
  - xorg
  - xsel
  - yubikey-manager
  - zathura

i3_packages:
  - arandr
  - dmenu
  - dunst
  - feh
  - ffmpegthumbnailer
  - gnome-keyring
  - i3lock
  - nemo
  - nemo-python
  - network-manager
  - network-manager-gnome
  - network-manager-openconnect
  - numlockx
  - openconnect
  - pasystray
  - pavucontrol
  - picom
  - pulseaudio
  - rofi
  - scrot
  - sddm
  - variety
  - w3m
  - zenity
