---
# tasks file for i3-configuration

- include_vars: "{{ item }}"
  with_first_found:
    - files:
        # allows for specific configs per host
        - "{{ ansible_hostname }}.yml"

- name: create the i3 conf dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, i3_config_dir) | path_join }}"
    state: directory
    mode: '0755'

- name: copy the i3 config file to the correct dir
  ansible.builtin.template:
    src: "i3_config.j2"
    dest: "{{ (ansible_user_dir, i3_config_dir, 'config') | path_join }}"
    mode: u+r-wx
    backup: yes
  notify:
    - i3_reload

- name: copy the rofi config file to the correct dir
  ansible.builtin.copy:
    src: "rofi.conf"
    dest: "{{ (ansible_user_dir, i3_config_dir, 'rofi.conf') | path_join }}"
    mode: u+r-wx
