---
# tasks file for polybar-configuration

- include_vars: "{{ item }}"
  with_first_found:
    - files:
        # allows for specific configs per host
        - "{{ ansible_hostname }}.yml"

- name: create the polybar conf dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, polybar_config_dir) | path_join }}"
    state: directory
    mode: '0755'

- name: copy the polybar config file to the correct dir
  ansible.builtin.template:
    src: "polybar_config"
    dest: "{{ (ansible_user_dir, polybar_config_dir, 'config') | path_join }}"
    mode: u+r-wx

- name: copy the polybar launchscript to the correct dir
  copy:
    src: "polybar_launcher.sh"
    dest: "{{ (ansible_user_dir, polybar_config_dir, 'polybar_launcher.sh') | path_join }}"
    mode: u=rx,g=,o=
