---

- name: copy the systemd unit and timer for the april fools joke
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ (ansible_user_dir, '.config/systemd/user', item) | path_join }}"
    mode: u=r,g=,o=
  with_items:
    - activate-linux.service
    - activate-linux.timer
  register: copy_systemd_units

- name: reload the systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
  when: copy_systemd_units.changed

- name: enable the systemd timer
  ansible.builtin.systemd:
    name: activate-linux.timer
    enabled: yes
    scope: user
