---
# tasks file for custom-scripts

- name: create directory for the scripts
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, script_dir) | path_join }}"
    state: directory
    mode: '0755'

- name: copy all the scripts into the script_dir
  copy:
    # the trailing slash ensures that all the folder content
    # and not the folder itself is copied!
    src: my_scripts/
    dest: "{{ (ansible_user_dir, script_dir) | path_join }}"
    mode: u+rx-w

- name: create the systemd-user dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, '.config/systemd/user') | path_join }}"
    state: directory
    mode: '0700'

- include_tasks: autoupdate_dotfiles.yml
- include_tasks: april_fools.yml
