---
# tasks file for custom-scripts

- name: create directory for the scripts
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, script_dir) | path_join }}"
    state: directory

- name: copy all the scripts into the script_dir
  ansible.posix.synchronize:
    # the trailing slash ensures that all the folder content
    # and not the folder itself is copied!
    src: my_scripts/
    dest: "{{ (ansible_user_dir, script_dir) | path_join }}"
    perms: no

- name: "set the permissions in {{ script_dir }}"
  file:
    dest: "{{ (ansible_user_dir, script_dir) | path_join }}"
    mode: u=rX,g=rX,o=
    recurse: yes

- name: create the systemd-user dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, '.config/systemd/user') | path_join }}"
    state: directory
    mode: '0700'

- name: create the xdg dir for the scripts
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, item.value) | path_join }}"
    state: directory
    mode: '0700'
  with_dict: "{{ xdg_base_dirs }}"

- name: install the autoupdater
  include_tasks: "timed_script.yml"
  vars:
    timed_script:
      unitname: "dotfiles"
      scriptname: "update_and_run.sh"

- name: install the update checker for the aur
  include_tasks: "timed_script.yml"
  vars:
    timed_script:
      unitname: "aur-update-notification"

- name: install the update checker for the normal packages
  include_tasks: "timed_script.yml"
  vars:
    timed_script:
      unitname: "archlinux-package-update-notification"

- include_tasks: april_fools.yml
