---

- name: copy the systemd unit and timer for the autoupdater
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ (ansible_user_dir, '.config/systemd/user', item) | path_join }}"
    mode: u=r,g=,o=
  with_items:
    - "{{ timed_script.unitname }}.service"
    - "{{ timed_script.unitname }}.timer"
  register: copy_systemd_units

- name: reload the systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  when: copy_systemd_units.changed

- name: copy the script
  ansible.builtin.template:
    src: "{{ timed_script.scriptname }}"
    dest: "{{ (ansible_user_dir, script_dir, timed_script.scriptname) | path_join }}"

- name: enable the systemd timer
  ansible.builtin.systemd:
    name: "{{ timed_script.unitname }}.timer"
    enabled: true
    scope: user
