---
# tasks file for git-configuration
- name: copy the git files
  copy:
    # omit the "." in the src
    src: "{{ item }}"
    dest: "{{ (ansible_user_dir, '.' + item ) | path_join }}"
    mode: u+r-wx
  with_items:
    - "gitignore"
    - "gitconfig"

- name: create the gh conf dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, gh_config_dir) | path_join }}"
    state: directory
    mode: '0755'

- name: copy the gh config file to the correct dir
  ansible.builtin.copy:
    src: "gh_config.yml"
    dest: "{{ (ansible_user_dir, gh_config_dir, 'config.yml') | path_join }}"
    mode: u+r-wx
