---
# tasks file for irc-configuration

- name: create config directory for weechat
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, weechat_config_dir) | path_join }}"
    state: directory
    mode: '0755'

- name: copy the weechat config files
  ansible.posix.synchronize:
    # the trailing slash ensures that all the folder content
    # and not the folder itself is copied!
    src: weechat/
    dest: "{{ (ansible_user_dir, weechat_config_dir) | path_join }}"

- name: also copy the irc config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ (ansible_user_dir, weechat_config_dir, item) | path_join }}"
  with_items:
    - irc.conf
    - plugins.conf
