---

# install the `robustirc-bridge` binary
# https://robustirc.net/

- name: get the gopath version
  ansible.builtin.shell:
    cmd: "go env GOPATH"
  register: gopath_cmd
  changed_when: false

- name: copy the systemd unit for robustirc
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ (ansible_user_dir, '.config/systemd/user', item) | path_join }}"
    mode: u=r
  with_items:
    - 'robustirc.service'
    - 'robustirc.socket'
  register: copy_robustirc_systemd_unit

- name: reload the systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
  when: copy_robustirc_systemd_unit.changed

- name: enable the unit for robustic
  ansible.builtin.systemd:
    name: robustirc.socket
    enabled: yes
    state: started
    scope: user
