---
# tasks file for shell-configuration

- name: set default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ default_shell }}"
  become: yes
  when: ansible_user_shell != default_shell

- name: install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: "{{ (ansible_user_dir, '.oh-my-zsh/') | path_join }}"

- name: copy the shell configs
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ (ansible_user_dir, '.' + item) | path_join }}"
    mode: u=r,g=,o=
    backup: yes
  with_items:
    - "zshrc"
    - "bashrc"

- name: install the extra zsh plugins
  ansible.builtin.git:
    repo: "{{ item.git_url }}"
    dest: "{{ (ansible_user_dir, '.oh-my-zsh/custom/plugins',  item.name ) | path_join }}"
    update: false
  with_items: "{{ extra_plugins }}"

- name: create the terminator config dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, xdg_base_dirs.XDG_CONFIG_HOME, 'terminator') | path_join }}"
    state: directory
    mode: '0755'

- name: copy the terminator config file to the correct dir
  ansible.builtin.copy:
    src: "terminator_config"
    dest: "{{ (ansible_user_dir, xdg_base_dirs.XDG_CONFIG_HOME, 'terminator', 'config') | path_join }}"
    mode: u+r-wx

- name: create the gdb config dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, xdg_base_dirs.XDG_CONFIG_HOME, 'gdb') | path_join }}"
    state: directory
    mode: '0755'

- name: copy the gdb config file to the correct dir
  ansible.builtin.copy:
    src: "gdbinit"
    dest: "{{ (ansible_user_dir, xdg_base_dirs.XDG_CONFIG_HOME, 'gdb', 'gdbinit') | path_join }}"
    mode: u+r-wx

- name: create the atuin config dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, xdg_base_dirs.XDG_CONFIG_HOME, 'atuin') | path_join }}"
    state: directory
    mode: '0755'

- name: copy the atuin config file to the correct dir
  ansible.builtin.copy:
    src: "atuin_config.toml"
    dest: "{{ (ansible_user_dir, xdg_base_dirs.XDG_CONFIG_HOME, 'atuin', 'config.toml') | path_join }}"
    mode: u+r-wx
