---
# tasks file for gopass-configuration

- name: create the gopass conf dir
  ansible.builtin.file:
    path: "{{ (ansible_user_dir, gopass_config_dir) | path_join }}"
    state: directory
    mode: '0755'

- name: copy the gopass config file to the correct dir
  ansible.builtin.template:
    src: "gopass_config.j2"
    dest: "{{ (ansible_user_dir, gopass_config_dir, 'config') | path_join }}"
    mode: u=r,g=,o=

- name: clone the gopass stores
  ansible.builtin.git:
    repo: "{{ item.git_url }}"
    dest: "{{ item.path }}"
    update: false
    accept_hostkey: true
  when: item.git_url is defined
  with_items: "{{ [default_store] + other_mounts }}"
