---
# tasks file for i3-install

- include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"

- name: "install all the packages"
  ansible.builtin.package:
    name: "{{ item.packages }}"
    state: present
  become: true
  with_items:
    - name: base
      packages: "{{ base_packages }}"
    - name: desktop
      packages: "{{ desktop_packages }}"
    - name: i3
      packages: "{{ i3_packages }}"

- include_tasks: "aur.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: enable the greeter
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ greeter_unit_name }}"
  become: yes
