---
# tasks file for i3-install

- include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"

- name: "install all the packages"
  ansible.builtin.package:
    name: "{{ item.packages }}"
    state: present
  become: true
  with_items:
    - name: base
      packages: "{{ base_packages }}"
    - name: desktop
      packages: "{{ desktop_packages }}"
    - name: i3
      packages: "{{ i3_packages }}"

- include_tasks: "archlinux.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: enable the greeter
  ansible.builtin.systemd:
    enabled: yes
    name: "{{ greeter_unit_name }}"
  become: yes

- name: create the wheel group
  ansible.builtin.group:
    name: wheel
    state: present
  become: yes

- name: create the user 'chris'
  ansible.builtin.user:
    name: chris
    shell: "{{ default_shell }}"
    groups: wheel
    append: yes
  become: yes

- name: allow the me to execute sudo
  ansible.builtin.blockinfile:
    path: /etc/sudoers.d/00-sudo
    block: |
       %wheel ALL=(ALL) ALL
       %wheel ALL=(ALL) NOPASSWD: /sbin/poweroff, /sbin/reboot, /sbin/shutdown
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: disable action on lid close
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "HandleLidSwitch=ignore"
    regexp: '^HandleLidSwitch='
    insertafter: '^#HandleLidSwitch='
  become: yes

- name: disable beep
  community.general.kernel_blacklist:
    name: pcspkr
    state: present
  become: yes

- name: enable time synchronization
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: yes
  become: yes

- name: persist the XDG_DIRS
  lineinfile:
    path: /etc/security/pam_env.conf
    line: "{{ item.key }}\tDEFAULT=@{HOME}/{{ item.value }}"
  with_dict: "{{ xdg_base_dirs }}"
  become: yes

- name: persist the other env vars
  lineinfile:
    path: /etc/security/pam_env.conf
    line: "{{ item.key }}\tDEFAULT={{ item.value }}"
  with_dict: "{{ environment_variables }}"
  become: yes

- name: enable yubikey smartcard discovery
  ansible.builtin.systemd:
    enabled: yes
    state: started
    name: pcscd.service
  become: yes
